#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2014 OpenWrt.org

START=99
STOP=99

USE_PROCD=1
PROG=/usr/sbin/router_server
LOG=/tmp/my_server.log

my_server_instance()
{
	local var_status
	config_get var_status $1 enable
	[ "${var_status}" = "0" ] && return 1

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_close_instance
}

start_service () {
	config_load "my_server_config"
	config_foreach my_server_instance my_server_section
}

stop_service () {
	killall -9 router_server
}

reload_service () {
	stop
	start
}

service_triggers () {
	procd_add_reload_trigger "my_server_config"
}
